[package]

name 			= "my_mio"
version			= "0.0.0"
license 		= "MIT"
authors			= ["hankai17 <hankai17@126.com>"]
description   	= "Lightweight non-blocking IO"
documentation 	= ""
homepage      	= ""
repository    	= ""
readme        	= "README.md"
keywords      	= ["io", "async", "non-blocking"]
categories    	= ["asynchronous"]
exclude       	= [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
]

[features]

[dependencies]
log      		= "0.4"
libc   			= "0.2.42"

[dev-dependencies]

